
spring.application.name=gitman

server.port=8888

git.repository.paths=C:/java/workospace/umlet, C:/java/workospace/sopaui, C:/java/workospace/lenteja-jdbc, C:/java/workospace/cosache, C:/java/workospace/gitinillo, C:/java/workospace/lispo2021
mvn.dir=C:/java/apache-maven-3.8.1/bin/mvn.cmd

#git.repository.paths=D:/gitrepos/cosache, D:/gitrepos/nplh-core, D:/gitrepos/nplh-open-connect, D:/gitrepos/devex, D:/gitrepos/nplh-installer

custache.prefix=templates/
custache.suffix=
