
spring.application.name=gitman

git.repository.paths=C:/java/workospace/sopaui, C:/java/workospace/lenteja-jdbc, C:/java/workospace/cosache, C:/java/workospace/gitinillo

custache.prefix=templates/
custache.suffix=
